---

apiVersion: fervid.us/v1alpha1
kind: ClusterClaim
metadata:
  name: cluster-01
spec:
  id: cluster-01
  compositionSelector:
    matchLabels:
      provider: aws
      cluster: eks
  parameters:
    nodeSize: small
    minNodeCount: 3

---

apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
data:
  password: bXlzcWw=

---

kind: AppClaim
metadata:
  name: wordpress
  namespace: production
spec:
  id: wordpress
  compositionSelector:
    matchLabels:
      type: backend-db
  parameters:
    namespace: production
    image: wordpress:latest
    port: 8080
    host: wordpress.lab.fervid.us

---

apiVersion: fervid.us/v1alpha1
kind: SQLClaim
metadata:
  name: wordpress
  namespace: production
spec:
  id: wordpress
  compositionSelector:
    matchLabels:
      provider: aws
      db: mysql
  parameters:
    version: \"13.4\"
    size: small
    namespace: production
  writeConnectionSecretToRef:
    name: wordpress