---

apiVersion: fervid.us/v1alpha1
kind: ClusterClaim
metadata:
  name: cluster-01
spec:
  id: cluster-01
  compositionSelector:
    matchLabels:
      provider: aws
      cluster: eks
  parameters:
    nodeSize: small
    minNodeCount: 3

---

apiVersion: v1
kind: Secret
metadata:
  name: rds-instance-credentials
data:
  password: cG9zdGdyZXM=

---

apiVersion: database.aws.crossplane.io/v1beta1
kind: RDSInstance
metadata:
  name: wordpress-db
spec:
  forProvider:
    dbInstanceClass: db.t3.micro
    masterUsername: masteruser
    masterUserPasswordSecretRef:
      name: rds-instance-credentials
      key: password
    allocatedStorage: 20
    engine: postgresql
    engineVersion: "16.4"
    region: us-east-1
  providerConfigRef:
    name: default

# ---

# apiVersion: fervid.us/v1alpha1
# kind: AppClaim
# metadata:
#   name: wordpress
# spec:
#   id: wordpress
#   compositionSelector:
#     matchLabels:
#       type: wordpress-db
#       location: remote
#   parameters:
#     namespace: development
#     image: wordpress:latest
#     port: 8080
#     host: wordpress.lab.fervid.us
#     dbSecret:
#       name: wordpress-db-credentials
#       namespace: cto-architecture
#     kubernetesProviderConfigName: cluster-01
