---

apiVersion: fervid.us/v1alpha1
kind: ClusterClaim
metadata:
  name: cluster-01
spec:
  id: cluster-01
  compositionSelector:
    matchLabels:
      provider: aws
      cluster: eks
  parameters:
    nodeSize: small
    minNodeCount: 3

---

apiVersion: v1
kind: Secret
metadata:
  name: wordpress-db-credentials
data:
  password: cG9zdGdyZXM=

# ---

# apiVersion: fervid.us/v1alpha1
# kind: AppClaim
# metadata:
#   name: wordpress
# spec:
#   id: wordpress
#   compositionSelector:
#     matchLabels:
#       type: wordpress-db
#       location: remote
#   parameters:
#     namespace: development
#     image: wordpress:latest
#     port: 8080
#     host: wordpress.lab.fervid.us
#     dbSecret:
#       name: wordpress-db-credentials
#       namespace: cto-architecture
#     kubernetesProviderConfigName: cluster-01

---

apiVersion: fervid.us/v1alpha1
kind: SQLClaim
metadata:
  name: wordpress-db
spec:
  id: wordpress-db
  compositionSelector:
    matchLabels:
      provider: aws
      db: postgresql
  parameters:
    version: "13"
    size: small
    databases:
      - wordpress-db
