apiVersion: fervid.us/v1alpha1
kind: ClusterClaim
metadata:
  name: cto-architeture
spec:
  id: cto-architecture
  compositionSelector:
    matchLabels:
      provider: aws
      cluster: eks
  parameters:
    nodeSize: medium
    minNodeCount: 1
    usage:
      enabled: true
    apps:
      argocd:
        enabled: true
        host: argocd.127.0.0.1.nip.io
        repoURL: https://github.com/prolixalias/crossplane-kubernetes
      dapr:
        enabled: true
      traefik:
        enabled: true
    namespaces:
    - development
    - production
