apiVersion: fervid.us/v1alpha1
kind: ClusterClaim
metadata:
  name: cto-architeture-team
spec:
  id: cto-architecture-team
  compositionSelector:
    matchLabels:
      provider: aws
      cluster: eks
  parameters:
    nodeSize: medium
    minNodeCount: 1
    usage:
      enabled: true
    apps:
      traefik:
        enabled: true
      argocd:
        enabled: true
        host: argocd.lab.fervid.us
        repoURL: https://github.com/prolixalias/crossplane-kubernetes
      dapr:
        enabled: true
    namespaces:
    - dev
    - production
