apiVersion: fervid.us/v1alpha1
kind: ClusterClaim
metadata:
  name: cto-architecture-team
spec:
  id: cto-architecture-team
  compositionSelector:
    matchLabels:
      provider: azure
      cluster: aks
  parameters:
    nodeSize: medium
    minNodeCount: 1
    namespaces:
      - development
      - production
    usage:
      # Usage is still in `alpha` and needs to be enabled by add `--set args='{"--enable-usages"}'` to `helm install`.
      enabled: true
