---

apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  # Set Resource Tracking Method (see https://docs.crossplane.io/knowledge-base/integrations/argo-cd-crossplane/#set-resource-tracking-method)
  application.resourceTrackingMethod: annotation
  resource.exclusions: |
    - apiGroups:
      - "*"
      kinds:
      - ProviderConfigUsage 

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cto-architecture
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/prolixalias/crossplane-kubernetes
    targetRevision: HEAD
    path: deploy/tenants/cto-architecture
  destination:
    server: https://kubernetes.default.svc
    namespace: cto-architecture
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
