name: deploy
on:
  push:
    branches:
      - main
jobs:
  create-cluster:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1
      - name: Install Devbox
        uses: jetpack-io/devbox-install-action@v0.11.0
        with:
          enable-cache: true
          project-path: .github/workflows
      - name: Setup
        run: |
          devbox --config .github/workflows run cluster-create && sleep 60
      - name: Validate
        run: |
          echo "This might be tricky."
      - name: Destroy
        run: |
          devbox --config .github/workflows run cluster-destroy
